apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datrics.fullname" . }}-{{ .Values.aiAnalyst.worker.name }}
  labels:
    {{- include "datrics.labels" . | nindent 4 }}
    {{- with.Values.aiAnalyst.worker.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "datrics.annotations" . | nindent 4 }}
    {{- with.Values.aiAnalyst.worker.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.aiAnalyst.worker.deployment.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "datrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "datrics.fullname" . }}-{{ .Values.aiAnalyst.worker.name }}
  template:
    metadata:
      annotations:
      {{- with .Values.aiAnalyst.worker.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.aiAnalyst.worker.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "datrics.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "datrics.fullname" . }}-{{ .Values.aiAnalyst.worker.name }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aiAnalyst.worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.aiAnalyst.worker.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.aiAnalyst.worker.name }}
          {{- with.Values.aiAnalyst.worker.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with.Values.aiAnalyst.worker.deployment.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "datrics.commonEnv" . | nindent 12 }}
            {{- include "datrics.aiAnalyst.env_vars" . | nindent 12 }}
            {{- with .Values.aiAnalyst.worker.deployment.extraEnv }}            
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.commonEnv }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "datrics.fullname" . }}-config
          image: "{{ .Values.images.aiAnalystImage.repository }}:{{ .Values.images.aiAnalystImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.aiAnalystImage.pullPolicy }}         
          {{- with .Values.aiAnalyst.worker.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.aiAnalyst.worker.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.aiAnalyst.worker.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.aiAnalyst.worker.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.aiAnalyst.worker.deployment.securityContext | nindent 12 }}
          {{- with .Values.aiAnalyst.worker.deployment.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.aiAnalyst.worker.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.aiAnalyst.worker.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiAnalyst.worker.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiAnalyst.worker.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
