apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datrics.fullname" . }}-{{ .Values.aiAnalyst.backend.name }}
  labels:
    {{- include "datrics.labels" . | nindent 4 }}
    {{- with.Values.aiAnalyst.backend.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "datrics.annotations" . | nindent 4 }}
    {{- with.Values.aiAnalyst.backend.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.aiAnalyst.backend.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "datrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "datrics.fullname" . }}-{{ .Values.aiAnalyst.backend.name }}
  template:
    metadata:
      annotations:
      {{- with .Values.aiAnalyst.backend.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.aiAnalyst.backend.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "datrics.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "datrics.fullname" . }}-{{ .Values.aiAnalyst.backend.name }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aiAnalyst.backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.aiAnalyst.backend.deployment.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Values.aiAnalyst.backend.name }}-initdb
          {{- with.Values.aiAnalyst.backend.initdb.command }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with.Values.aiAnalyst.backend.initdb.args }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
            {{- include "datrics.commonEnv" . | nindent 10 }}
            {{- include "datrics.aiAnalyst.env_vars" . | nindent 10 }}
            {{- with .Values.aiAnalyst.backend.initdb.extraEnv }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- with .Values.commonEnv }}
              {{ toYaml . | nindent 10 }}
            {{- end }}
          image: "{{ .Values.images.aiAnalystImage.repository }}:{{ .Values.images.aiAnalystImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.aiAnalystImage.pullPolicy }}
          resources:
            {{- toYaml .Values.aiAnalyst.backend.initdb.resources | nindent 12 }}
      containers:
        {{- if .Values.aiAnalyst.backend.flower.enabled }}
        - name: {{ .Values.aiAnalyst.backend.name }}-flower
          {{- with.Values.aiAnalyst.backend.flower.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "datrics.commonEnv" . | nindent 12 }}            
            {{- with .Values.aiAnalyst.backend.flower.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- include "datrics.aiAnalyst.env_vars" . | nindent 12 }}
            {{- with .Values.commonEnv }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "datrics.fullname" . }}-config
          image: "{{ .Values.images.aiAnalystImage.repository }}:{{ .Values.images.aiAnalystImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.aiAnalystImage.pullPolicy }}
          ports:
            - name: flower
              containerPort: {{ .Values.aiAnalyst.backend.flower.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.aiAnalyst.backend.flower.resources | nindent 12 }}
        {{- end }}
        - name: {{ .Values.aiAnalyst.backend.name }}-api
          {{- with.Values.aiAnalyst.backend.api.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with.Values.aiAnalyst.backend.api.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "datrics.commonEnv" . | nindent 12 }}
            - name: UVICORN_PORT
              value: {{ .Values.aiAnalyst.backend.api.containerPort | quote }}            
            - name: ADMIN_EMAIL
              value: {{ .Values.aiAnalyst.config.admin.email | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.aiAnalyst.config.admin.password | quote }}
            - name: ADMIN_SECRET
              value: {{ .Values.aiAnalyst.config.admin.secret | quote }}
            - name: PRINT_CONSOLE
              value: {{ .Values.aiAnalyst.config.printConsole | quote }}
            {{- include "datrics.aiAnalyst.env_vars" . | nindent 12 }}
            {{- with .Values.aiAnalyst.backend.api.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.commonEnv }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "datrics.fullname" . }}-config
          image: "{{ .Values.images.aiAnalystImage.repository }}:{{ .Values.images.aiAnalystImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.aiAnalystImage.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.aiAnalyst.backend.api.containerPort }}
              protocol: TCP
          {{- with .Values.aiAnalyst.backend.api.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.aiAnalyst.backend.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.aiAnalyst.backend.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.aiAnalyst.backend.api.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.aiAnalyst.backend.api.securityContext | nindent 12 }}
          {{- with .Values.aiAnalyst.backend.api.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.aiAnalyst.backend.api.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.aiAnalyst.backend.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.aiAnalyst.backend.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiAnalyst.backend.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiAnalyst.backend.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiAnalyst.backend.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
