{{- if .Values.aiAnalyst.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiAnalyst.worker.serviceAccountName" . }}
  labels:
    {{- include "datrics.labels" . | nindent 4 }}
    {{- with.Values.aiAnalyst.worker.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "datrics.annotations" . | nindent 4 }}
    {{- with.Values.aiAnalyst.worker.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}