apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "datrics.fullname" . }}-{{ .Values.api.setup.name }}
  labels:
    {{- include "datrics.labels" . | nindent 4 }}
    {{- with.Values.api.setup.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      annotations:
      {{- with .Values.api.setup.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.api.setup.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "datrics.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "datrics.fullname" . }}-{{ .Values.api.setup.name }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.setup.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.api.name }}-setup
        image: "{{ .Values.images.apiImage.repository }}:{{ .Values.images.apiImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.images.apiImage.pullPolicy }}
        command: ["npm", "run", "prod"]
        resources:
          {{- toYaml .Values.api.setup.resources | nindent 12 }}
        env:
          {{- include "datrics.api.env_vars" . | nindent 12 }}
      restartPolicy: Never