{{- if or .Values.api.serviceAccount.create .Values.common.workers_mode -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api.serviceAccountName" . }}
  labels:
    {{- include "datrics.labels" . | nindent 4 }}
    {{- with.Values.api.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "datrics.annotations" . | nindent 4 }}
    {{- with.Values.api.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
