{{- if .Values.common.workers_mode -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-deployments-to-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-deployments
subjects:
- kind: ServiceAccount
  name: {{ include "api.serviceAccountName" . }}
{{- end }}