{{- if .Values.common.workers_mode -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-deployments
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
{{- end }}